import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Wtch from "@/app/system"; 
import Layout from "@/element/loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {return (<html lang="en" className="overflow-x-hidden scroll-smooth"><body className={`${geistSans.variable} ${geistMono.variable} overflow-x-hidden antialiased`}><Wtch /><Layout>{children}</Layout></body></html>);}
